language: python
addons:
  postgresql: "9.6"
python:
  - "3.6"
before_script:
  - psql -c 'create database judyst_backend;' -U postgres
  - python3 manage.py makemigrations
  - python3 manage.py migrate
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python3 ./gen_settings.py
  - cat ./judyst_backend/local_settings.py
